---
title: "Presentation Ninja"
subtitle: "⚔<br/>with xaringan"
author: "Yihui Xie"
institute: "RStudio, PBC"
date: "2016/12/12 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
```{r, presentation-options, echo=F}
knitr::opts_chunk$set(echo=F)
```

```{r, lib, echo=T, message=F, warning=F}
library(tidyverse)
library(ds4ling)
library(untidydata)
library(plot3D)
library(patchwork)
```


```{r}
glimpse(language_diversity)

ld <- language_diversity %>% 
  filter(., Continent == "Africa") %>% 
  pivot_wider(names_from = "Measurement", values_from = "Value") %>% 
  mutate(., logPop = log(Population), 
            logArea = log(Area))
head(ld)
```

---

# A plot

.pull-left[

```{r, fig.height=5, fig.width=11, message=F, fig.retina=2}
p1 <- ld %>% 
ggplot(., aes(x = Population, y = Langs, color = Area, label = Country)) +
  geom_text() + 
  geom_smooth(method = lm) +
  labs(title = "HI", subtitle = "hello", x = "Pop.", y = "# of Langs",
       caption = "a caption") +
  theme_minimal(base_size = 20, base_family = "Times")
```

]

.pull-right[
```{r, fig.height=6, fig.width=6, message=F, fig.retina=2}
p2 <- ld %>% 
ggplot(., aes(x = logPop, y = Langs, color = logArea, label = Country)) +
  geom_text() + 
  geom_smooth(method = lm) +
  labs(title = "HI", subtitle = "hello", x = "Pop.", y = "# of Langs",
       caption = "a caption") +
  theme_minimal(base_size = 20, base_family = "Times")
```

]

---
.pull-left[

- hi
- info
- pull

]
.pull-right[
```{r, fig.height=6, fig.width=6, message=F, fig.retina=2}
ld %>% 
ggplot(., aes(x = logPop, y = Langs, color = logArea, label = Country)) +
  geom_text() + 
  geom_smooth(method = lm) +
  labs(title = "HI", subtitle = "hello", x = "Pop.", y = "# of Langs",
       caption = "a caption") +
  theme_minimal(base_size = 20, base_family = "Times")
```

]

---
```{r, fig.width = 12}
p1 + p2
```

---

.pull-left[

- stuff

]

--

.pull-left[

- hi

]

--

.pull-right[

```{r, fig.width = 12}
p1 / p2
```

]